"""Tests for spinquest_sim.games.crash against the published references."""

import hashlib
import importlib.util
import math
import sys
import time
from pathlib import Path

import numpy as np
import pytest

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from spinquest_sim import rng as sq_rng  # noqa: E402
from spinquest_sim.games import crash as crash_mod  # noqa: E402
from spinquest_sim.games.crash import (  # noqa: E402
    EDGE_MULTIPLIER,
    HOUSE_EDGE,
    MAX_CASHOUT,
    STAKE_CHAIN_LENGTH,
    STAKE_SALT,
    STAKE_TERMINATING_HASH,
    TWO32,
    EXTERNAL_BEACONS,
    CommitmentOrderError,
    CommitmentOrderWarning,
    Crash,
    HashChain,
    is_external_commitment,
    analytic_table,
    build_hash_chain,
    crash_int_from_hash,
    crash_point_from_float,
    crash_point_from_hash,
    crash_point_from_int,
    instant_bust_probability,
    next_chain_hash,
    simulate_chain_targets,
    simulate_targets,
    verify_game_hash,
    win_count,
    win_probability,
    win_probability_ideal,
)
from spinquest_sim.rng import BulkRng  # noqa: E402


def _load_validator():
    spec = importlib.util.spec_from_file_location(
        "validate_crash", _ROOT / "scripts" / "validate_crash.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


VAL = _load_validator()

SERVER = "a3f1c8d92b6e4a7f5c0d9b8e1f2a3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b"
CLIENT = "test-crash-client"
TARGETS = [1.01, 1.5, 2.0, 3.0, 5.0, 10.0, 100.0, 1000.0]
# A test salt for chains generated by the tests (never STAKE_SALT — that is
# reserved for replaying Stake's published 2019 chain).
TEST_SALT = hashlib.sha256(b"test-crash-salt").hexdigest()
# A structured external commitment CLAIM (verifier-resolvable beacon +
# index) — the ONLY kind of salt_source that can EVER yield
# fair_ordering=True, and only after verify_salt_against_beacon succeeds.
BEACON_SOURCE = {"beacon": "bitcoin", "height": 1_000_000}
# Structurally plausible beacon values for the claim/verify tests: a
# Bitcoin block hash must have >= 8 leading zero nibbles; drand randomness
# is unstructured 64-char hex.
FAKE_BLOCK_SALT = "0" * 10 + hashlib.sha256(b"plausible block").hexdigest()[10:]
DRAND_SALT = hashlib.sha256(b"plausible drand value").hexdigest()
# Bitcoin block 1 — a REAL, long-published beacon value (mined 2009-01-09):
# the round-5 seed-grinding exploit binds this genuine hash so a verifier's
# value lookup matches byte-for-byte; only its publication TIME kills it.
BITCOIN_BLOCK_1_HASH = (
    "00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048"
)
BITCOIN_BLOCK_1_TIME = 1_231_469_665.0  # 2009-01-09 UTC


def _bound_chain(secret: str, length: int) -> HashChain:
    """Honest-protocol chain: commit first, bind TEST_SALT afterwards."""
    hc = HashChain(secret, length=length)
    hc.bind_salt(TEST_SALT, salt_source="test fixture")
    return hc


# ---------------------------------------------------------------------------
# Published constants and formula (references/stake/crash.md)
# ---------------------------------------------------------------------------

class TestPublishedConstants:
    def test_constants_match_reference_document(self):
        ref = VAL.parse_stake_reference()
        assert ref["terminating_hash"] == STAKE_TERMINATING_HASH
        assert ref["salt"] == STAKE_SALT
        assert ref["chain_length"] == STAKE_CHAIN_LENGTH
        assert ref["house_edge"] == HOUSE_EDGE
        assert ref["max_cashout"] == MAX_CASHOUT
        assert ref["formula_found"]

    def test_edge_multiplier_verbatim(self):
        # verbatim (1 - 0.01); in float64 this equals the literal 0.99 exactly
        assert EDGE_MULTIPLIER == 0.99
        assert EDGE_MULTIPLIER == 1 - 0.01


class TestFormula:
    def test_extreme_ints(self):
        # int = 2^32 - 1: (2^32 / 2^32) * 0.99 = 0.99 -> Math.max -> 1
        assert crash_point_from_int(TWO32 - 1) == 1.0
        # int = 0: raw max multiplier
        assert crash_point_from_int(0) == (2 ** 32 / 1) * (1 - 0.01)
        assert crash_point_from_int(0) > MAX_CASHOUT

    def test_matches_verbatim_js_expression(self):
        for k in [0, 1, 2, 99, 12345, 123456789, 2**31, TWO32 - 2, TWO32 - 1]:
            expected = max(1, (2 ** 32 / (k + 1)) * (1 - 0.01))
            assert crash_point_from_int(k) == expected

    def test_weakly_decreasing(self):
        ks = np.linspace(0, TWO32 - 1, 10001).astype(np.int64)
        vals = [crash_point_from_int(int(k)) for k in ks]
        assert all(a >= b for a, b in zip(vals, vals[1:]))

    def test_rejects_out_of_range_int(self):
        with pytest.raises(ValueError):
            crash_point_from_int(-1)
        with pytest.raises(ValueError):
            crash_point_from_int(TWO32)

    def test_hmac_against_independent_construction(self):
        # Manual HMAC-SHA256 (ipad/opad from first principles) — independent
        # of the hmac module used by the implementation.
        game_hash = hashlib.sha256(b"test vector").hexdigest()
        key = game_hash.encode()  # 64 bytes -> padded to block size 64
        assert len(key) == 64
        ipad = bytes(b ^ 0x36 for b in key)
        opad = bytes(b ^ 0x5C for b in key)
        inner = hashlib.sha256(ipad + STAKE_SALT.encode()).digest()
        digest = hashlib.sha256(opad + inner).digest()
        expected_int = int(digest.hex()[:8], 16)  # parseInt(hex.substr(0,8), 16)
        # STAKE_SALT passed explicitly: replay-verification of Stake's
        # published chain is its only legitimate use.
        assert crash_int_from_hash(game_hash, STAKE_SALT) == expected_int
        assert crash_point_from_hash(game_hash, STAKE_SALT) == crash_point_from_int(
            expected_int
        )

    def test_parseint_equals_first_four_bytes(self):
        game_hash = "ab" * 32
        digest_hex = __import__("hmac").new(
            game_hash.encode(), STAKE_SALT.encode(), hashlib.sha256
        ).hexdigest()
        assert crash_int_from_hash(game_hash, STAKE_SALT) == int(digest_hex[:8], 16)


# ---------------------------------------------------------------------------
# Hash chain mechanics
# ---------------------------------------------------------------------------

class TestHashChain:
    def test_chain_construction(self):
        chain = build_hash_chain("secret", 50)
        assert len(chain) == 50
        assert chain[0] == hashlib.sha256(b"secret").hexdigest()
        for prev, nxt in zip(chain, chain[1:]):
            assert nxt == hashlib.sha256(prev.encode()).hexdigest()
            assert nxt == next_chain_hash(prev)

    def test_verify_game_hash_steps(self):
        chain = build_hash_chain("secret", 50)
        terminating = chain[-1]
        # game g (1-indexed, newest-first) is chain[-1 - g]; verifies in g steps
        for g in [1, 2, 5, 49]:
            assert verify_game_hash(chain[-1 - g], terminating, 100) == g
        assert verify_game_hash("00" * 32, terminating, 20) is None

    def test_hashchain_play_order_and_exhaustion(self):
        hc = _bound_chain("secret", 6)
        chain = build_hash_chain("secret", 6)
        assert hc.terminating_hash == chain[-1]
        assert hc.games_remaining == 5
        popped = [hc.pop_hash() for _ in range(5)]
        assert [g for g, _ in popped] == [1, 2, 3, 4, 5]
        assert [h for _, h in popped] == chain[-2::-1]  # newest first, no term.
        with pytest.raises(RuntimeError):
            hc.pop_hash()

    def test_crash_points_match_scalar(self):
        hc = _bound_chain("secret", 20)
        pts = hc.crash_points(10)
        chain = build_hash_chain("secret", 20)
        expected = [crash_point_from_hash(h, TEST_SALT) for h in chain[-2:-12:-1]]
        assert pts == expected

    def test_stream_matches_hashchain_bitwise(self):
        n = 500
        ints, terminating = crash_mod._stream_chain_ints(
            "stream-secret", n, TEST_SALT, progress=False
        )
        chain = build_hash_chain("stream-secret", n + 1)
        assert terminating == chain[-1]
        expected = [crash_int_from_hash(h, TEST_SALT) for h in chain[-2::-1]]
        assert ints.tolist() == expected

    def test_stream_terminator_matches_chain(self):
        n = 200
        term = crash_mod._stream_chain_terminator("commit-secret", n,
                                                  progress=False)
        chain = build_hash_chain("commit-secret", n + 1)
        assert term == chain[-1]

    def test_build_chain_guards(self):
        with pytest.raises(ValueError):
            build_hash_chain("s", 1)
        with pytest.raises(ValueError):
            build_hash_chain("s", 5_000_000)


# ---------------------------------------------------------------------------
# Analytics
# ---------------------------------------------------------------------------

class TestAnalytics:
    @pytest.mark.parametrize("w", TARGETS + [1.23, 33.33, 250.0, 1e6])
    def test_win_count_boundary_is_exact(self, w):
        n = win_count(w)
        assert 0 < n < TWO32
        # bisection boundary: crash(n-1) >= w > crash(n)
        assert crash_point_from_int(n - 1) >= w
        assert crash_point_from_int(n) < w

    @pytest.mark.parametrize("w", TARGETS)
    def test_win_probability_close_to_ideal(self, w):
        p, ideal = win_probability(w), win_probability_ideal(w)
        # quantization: |p - 0.99/w| <= ~2/2^32
        assert abs(p - ideal) <= 2.5 / TWO32
        assert ideal == 0.99 / w

    @pytest.mark.parametrize("w", TARGETS + [1e6])
    def test_rtp_within_quantization_bound_of_099(self, w):
        game = Crash(w)
        assert abs(game.rtp - 0.99) <= game.rtp_quantization_bound + 1e-12
        assert game.rtp == w * game.win_probability
        assert game.house_edge == 1.0 - game.rtp

    def test_instant_bust_near_one_percent(self):
        p = instant_bust_probability()
        assert abs(p - 0.01) < 1e-4

    def test_variance_matches_closed_form(self):
        for w in TARGETS:
            game = Crash(w)
            p = game.win_probability
            assert game.variance_per_unit == pytest.approx(
                w * w * p - (w * p) ** 2, rel=1e-12
            )
            # ideal closed form sqrt(0.99 w - 0.9801), quantization-close
            assert game.std_per_unit == pytest.approx(
                game.std_per_unit_ideal, rel=1e-3
            )

    def test_target_validation(self):
        for bad in [1.0, 0.5, 0.0, -2.0, 1_000_000.01, float("inf"), float("nan")]:
            with pytest.raises(ValueError):
                Crash(bad)
        Crash(1.01)
        Crash(MAX_CASHOUT)

    def test_analytic_table_and_summary_shape(self):
        rows = analytic_table([2.0, 10.0])
        assert [r["target"] for r in rows] == [2.0, 10.0]
        summary = Crash(2.0).analytic_summary()
        assert set(summary) == {"rtp", "house_edge", "std_per_unit", "config"}
        assert summary["config"]["game"] == "crash"


# ---------------------------------------------------------------------------
# Provably-fair single rounds
# ---------------------------------------------------------------------------

class TestPlayRounds:
    def test_play_round_chain(self):
        hc = _bound_chain("secret", 30)
        game = Crash(2.0)
        for _ in range(10):
            _, game_hash = hc.pop_hash()
            res = game.play_round(game_hash, hc.salt)
            assert res["crash_point"] == crash_point_from_hash(game_hash, hc.salt)
            assert res["win"] == (res["crash_point"] >= 2.0)
            assert res["payout"] == (2.0 if res["win"] else 0.0)
            assert res["verification"]["mechanism"] == "hash_chain"
            assert verify_game_hash(
                res["verification"]["game_hash"], hc.terminating_hash, 30
            ) is not None

    def test_play_round_seedpair_matches_stream_float(self):
        game = Crash(2.0)
        for nonce in range(8):
            res = game.play_round_seedpair(SERVER, CLIENT, nonce)
            f = sq_rng.generate_floats(SERVER, CLIENT, nonce, 0, 1)[0]
            assert res["crash_point"] == crash_point_from_float(f)
            assert res["event_int"] == int(f * 2 ** 32)
            assert res["win"] == (res["crash_point"] >= 2.0)

    def test_float_to_int_recovery_is_exact(self):
        # lattice floats k/2^32 recover k exactly
        for k in [0, 1, 255, 65535, 2**31 - 1, TWO32 - 1]:
            f = k / TWO32
            assert int(f * float(TWO32)) == k
            assert crash_point_from_float(f) == crash_point_from_int(k)
        with pytest.raises(ValueError):
            crash_point_from_float(1.0)


# ---------------------------------------------------------------------------
# Vectorized simulators
# ---------------------------------------------------------------------------

class TestSimulate:
    def test_bulk_rows_match_scalar_seedpair(self):
        n = 64
        bulk = BulkRng(server_seed=SERVER, client_seed=CLIENT, nonce_start=0)
        k = bulk.floats(n) * float(TWO32)
        crash_vec = np.maximum(1.0, (float(TWO32) / (k + 1.0)) * EDGE_MULTIPLIER)
        game = Crash(2.0)
        for i in range(n):
            res = game.play_round_seedpair(SERVER, CLIENT, i)
            assert res["crash_point"] == crash_vec[i]

    def test_simulate_bulk_statistics(self):
        game = Crash(2.0)
        bulk = BulkRng(server_seed=SERVER, client_seed=CLIENT, nonce_start=0)
        res = game.simulate(400_000, bulk=bulk, progress=False)
        for key in ("rtp", "house_edge", "std_per_unit", "config"):
            assert key in res
        assert res["n_rounds"] == 400_000
        assert res["wins"] == round(res["win_rate"] * 400_000)
        assert abs(res["z_score"]) <= 4.0  # deterministic seed; sanity bar
        assert res["rtp"] == res["win_rate"] * 2.0
        assert res["verification"]["mechanism"] == "seed_pair_bulk"
        assert res["verification"]["nonce_range"] == (0, 400_000)

    def test_simulate_targets_shares_stream(self):
        bulk1 = BulkRng(server_seed=SERVER, client_seed=CLIENT, nonce_start=0)
        multi = simulate_targets([1.5, 2.0, 10.0], 200_000, bulk=bulk1,
                                 progress=False)
        assert multi["n_rounds"] == 200_000
        bulk2 = BulkRng(server_seed=SERVER, client_seed=CLIENT, nonce_start=0)
        single = Crash(2.0).simulate(200_000, bulk=bulk2, progress=False)
        row = next(r for r in multi["targets"] if r["config"]["target"] == 2.0)
        assert row["wins"] == single["wins"]

    def test_simulate_chain_bit_matches_hashchain(self):
        # two-phase mode: commit first, salt self-drawn afterwards — the
        # timestamps are honest but the salt has NO external commitment, so
        # the record must say operator_drawn / fair_ordering False.
        n = 2_000
        seed = "chain-sim-secret"
        res = simulate_chain_targets([2.0], n, secret_seed=seed, progress=False)
        commitment = res["verification"]["commitment"]
        assert commitment["fair_ordering"] is False
        assert commitment["order"] == "operator_drawn_after_commitment"
        assert "external commitment" in commitment["note"]
        assert (
            commitment["terminating_hash_committed_at_unix"]
            <= commitment["salt_bound_at_unix"]
        )
        # replay the whole campaign with a HashChain bound to the SAME salt
        hc = HashChain(seed, length=n + 1)
        hc.bind_salt(res["verification"]["salt"])
        assert res["verification"]["terminating_hash"] == hc.terminating_hash
        wins_scalar = sum(1 for p in hc.crash_points(n) if p >= 2.0)
        assert res["targets"][0]["wins"] == wins_scalar

    def test_simulate_chain_statistics(self):
        game = Crash(1.5)
        # deterministic (caller-supplied salt) -> reproducible mode warns
        with pytest.warns(CommitmentOrderWarning):
            res = game.simulate_chain(150_000, secret_seed="stats-secret",
                                      salt=TEST_SALT, progress=False)
        assert abs(res["z_score"]) <= 4.0
        assert res["verification"]["mechanism"] == "hash_chain"
        assert res["verification"]["chain_length"] == 150_001
        assert res["verification"]["commitment"]["fair_ordering"] is False

    def test_int_domain_threshold_equals_float_comparison(self):
        # chain sim counts wins as int < win_count; must equal crash >= w
        rng = np.random.default_rng(7)
        ks = rng.integers(0, TWO32, size=50_000)
        crash = np.maximum(1.0, (float(TWO32) / (ks + 1.0)) * EDGE_MULTIPLIER)
        for w in [1.01, 2.0, 10.0, 1000.0]:
            assert int(np.count_nonzero(crash >= w)) == int(
                np.count_nonzero(ks < win_count(w))
            )

    def test_rejects_bad_round_counts(self):
        with pytest.raises(ValueError):
            simulate_targets([2.0], 0)
        with pytest.raises(ValueError):
            simulate_chain_targets([2.0], -5)


# ---------------------------------------------------------------------------
# Provable-fairness commitment ordering (terminating hash FIRST, salt SECOND)
# ---------------------------------------------------------------------------

class TestCommitmentOrdering:
    def test_stake_salt_refused_for_new_chain_at_init(self):
        with pytest.raises(CommitmentOrderError):
            HashChain("fresh-secret", length=6, salt=STAKE_SALT)

    def test_stake_salt_refused_at_bind(self):
        hc = HashChain("fresh-secret", length=6)
        with pytest.raises(CommitmentOrderError):
            hc.bind_salt(STAKE_SALT)

    def test_stake_salt_refused_in_chain_simulator(self):
        with pytest.raises(CommitmentOrderError):
            simulate_chain_targets([2.0], 100, secret_seed="s",
                                   salt=STAKE_SALT, progress=False)

    def test_cannot_play_before_salt_bound(self):
        hc = HashChain("fresh-secret", length=6)
        assert hc.salt is None
        with pytest.raises(RuntimeError, match="no salt bound"):
            hc.pop_hash()
        with pytest.raises(RuntimeError, match="no salt bound"):
            hc.crash_points(1)
        # the commitment IS available before the salt exists
        assert len(hc.terminating_hash) == 64
        assert hc.commitment["fair_ordering"] is False  # unbound yet

    def test_salt_binds_exactly_once(self):
        hc = HashChain("fresh-secret", length=6)
        hc.bind_salt(TEST_SALT)
        with pytest.raises(CommitmentOrderError, match="already bound"):
            hc.bind_salt(hashlib.sha256(b"other").hexdigest())

    def test_salt_predating_commitment_raises(self):
        hc = HashChain("fresh-secret", length=6)
        stale = hashlib.sha256(b"old block").hexdigest()
        with pytest.raises(CommitmentOrderError, match="predates"):
            hc.bind_salt(stale, revealed_at=hc.committed_at - 3600.0)

    def test_beacon_claim_then_verification_certifies_fair(self):
        # The full honest protocol: commit -> bind a structured beacon
        # CLAIM (mandatory revealed_at, structurally plausible salt) ->
        # the VERIFIER resolves the named index out-of-band and calls
        # verify_salt_against_beacon.  Only then fair_ordering=True.
        for source, salt in (
            (BEACON_SOURCE, FAKE_BLOCK_SALT),
            ({"beacon": "drand", "round": 3_366_570}, DRAND_SALT),
        ):
            hc = HashChain("fresh-secret", length=6)
            time.sleep(0.002)
            revealed = time.time()
            hc.bind_salt(salt, salt_source=source, revealed_at=revealed)
            # a claim alone is NOT a certification
            c = hc.commitment
            assert hc.fair_ordering is False
            assert hc.fair_ordering_claimed is True
            assert c["order"] == "external_commitment_claimed_unverified"
            assert c["fair_ordering"] is False
            assert "verify_salt_against_beacon" in c["note"]
            # verifier's out-of-band resolution: value matches, published
            # strictly after the commitment
            rec = hc.verify_salt_against_beacon(salt, resolved_time=revealed)
            assert hc.fair_ordering is True
            assert rec["order"] == "terminating_hash_first"
            assert rec["fair_ordering"] is True
            assert rec["beacon_verification"]["verified"] is True
            assert rec["salt_bound_at_unix"] >= rec[
                "terminating_hash_committed_at_unix"
            ]
            assert rec["salt_source"] == source
            assert "note" not in rec

    def test_beacon_claim_requires_revealed_at(self):
        hc = HashChain("fresh-secret", length=6)
        with pytest.raises(CommitmentOrderError, match="revealed_at"):
            hc.bind_salt(FAKE_BLOCK_SALT, salt_source=BEACON_SOURCE)

    def test_beacon_claim_future_dated_revealed_at_refused(self):
        hc = HashChain("fresh-secret", length=6)
        with pytest.raises(CommitmentOrderError, match="future"):
            hc.bind_salt(FAKE_BLOCK_SALT, salt_source=BEACON_SOURCE,
                         revealed_at=time.time() + 3600.0)

    def test_beacon_claim_past_reveal_refused_at_bind(self):
        # honestly attesting an ALREADY-PUBLISHED beacon value is refused
        # on the spot — the named index must be a future one
        hc = HashChain("fresh-secret", length=6)
        with pytest.raises(CommitmentOrderError, match="predates"):
            hc.bind_salt(BITCOIN_BLOCK_1_HASH,
                         salt_source={"beacon": "bitcoin", "height": 1},
                         revealed_at=BITCOIN_BLOCK_1_TIME)

    def test_bitcoin_claim_structurally_impossible_salt_refused(self):
        # a claimed Bitcoin block hash with < 8 leading zero nibbles is
        # impossible at ANY height (difficulty-1 proof-of-work floor)
        hc = HashChain("fresh-secret", length=6)
        time.sleep(0.002)
        with pytest.raises(CommitmentOrderError, match="leading zero"):
            hc.bind_salt(TEST_SALT, salt_source=BEACON_SOURCE,
                         revealed_at=time.time())
        for bad in ("not-hex-at-all", "abc123", FAKE_BLOCK_SALT[:-2]):
            hc2 = HashChain("fresh-secret", length=6)
            time.sleep(0.002)
            with pytest.raises(CommitmentOrderError, match="hex"):
                hc2.bind_salt(bad, salt_source=BEACON_SOURCE,
                              revealed_at=time.time())

    def test_verify_requires_a_bound_beacon_claim(self):
        hc = HashChain("fresh-secret", length=6)
        with pytest.raises(RuntimeError, match="no salt bound"):
            hc.verify_salt_against_beacon(TEST_SALT, time.time())
        hc.bind_salt(TEST_SALT, salt_source="free text")
        with pytest.raises(CommitmentOrderError, match="nothing"):
            hc.verify_salt_against_beacon(TEST_SALT, time.time())

    def test_verify_mismatched_value_refutes_claim(self):
        hc = HashChain("fresh-secret", length=6)
        time.sleep(0.002)
        hc.bind_salt(DRAND_SALT,
                     salt_source={"beacon": "drand", "round": 3_366_570},
                     revealed_at=time.time())
        other = hashlib.sha256(b"what drand actually published").hexdigest()
        with pytest.raises(CommitmentOrderError, match="does not match"):
            hc.verify_salt_against_beacon(other, resolved_time=time.time())
        assert hc.fair_ordering is False
        c = hc.commitment
        assert c["order"] == "external_commitment_refuted"
        assert "REFUTED" in c["note"]
        assert c["beacon_verification"]["verified"] is False

    def test_seed_grind_against_published_beacon_not_certified_fair(self):
        # THE ROUND-5 EXPLOIT: grind the SECRET SEED against an
        # already-published beacon value (Bitcoin block 1's hash) until the
        # first rounds all bust below 2x, then bind the GENUINE block hash
        # with {"beacon": "bitcoin", "height": 1} — a verifier's value
        # lookup matches byte-for-byte.  Every certification path must die.
        salt = BITCOIN_BLOCK_1_HASH
        tries, seed = 0, None
        while seed is None:
            cand = f"grind-seed {tries}"
            chain = build_hash_chain(cand, 5)
            if all(crash_point_from_hash(h, salt) < 2.0
                   for h in chain[-2:-5:-1]):
                seed = cand
            tries += 1
        hc = HashChain(seed, length=5)
        source = {"beacon": "bitcoin", "height": 1}
        # (a) claim without revealed_at: refused outright
        with pytest.raises(CommitmentOrderError, match="revealed_at"):
            hc.bind_salt(salt, salt_source=source)
        # (b) honest revealed_at (2009): refused outright
        with pytest.raises(CommitmentOrderError, match="predates"):
            hc.bind_salt(salt, salt_source=source,
                         revealed_at=BITCOIN_BLOCK_1_TIME)
        # (c) LIE about the reveal time: binds only as an UNVERIFIED claim
        time.sleep(0.002)
        hc.bind_salt(salt, salt_source=source, revealed_at=time.time())
        assert all(p < 2.0 for p in hc.crash_points(3))  # rig works...
        assert hc.fair_ordering is False                 # ...never certified
        assert (hc.commitment["order"]
                == "external_commitment_claimed_unverified")
        # (d) the verifier resolves block 1 out-of-band: the value matches
        # byte-for-byte, but its TRUE publication time predates the
        # commitment -> claim refuted permanently
        with pytest.raises(CommitmentOrderError, match="BEFORE the chain"):
            hc.verify_salt_against_beacon(
                salt, resolved_time=BITCOIN_BLOCK_1_TIME
            )
        assert hc.fair_ordering is False
        assert hc.commitment["order"] == "external_commitment_refuted"
        assert "REFUTED" in hc.commitment["note"]
        # (e) a refuted claim cannot be revived, even by a later lying
        # verify call with a fabricated post-commitment resolved_time
        with pytest.raises(CommitmentOrderError, match="already refuted"):
            hc.verify_salt_against_beacon(salt, resolved_time=time.time())
        assert hc.fair_ordering is False

    def test_bind_without_external_commitment_is_not_fair(self):
        # The general rule: no external commitment => not fair, even with
        # honest timestamps and an operator-supplied revealed_at attestation.
        hc = HashChain("fresh-secret", length=6)
        hc.bind_salt(TEST_SALT, salt_source="attested test source",
                     revealed_at=hc.committed_at + 1.0)
        c = hc.commitment
        assert hc.fair_ordering is False
        assert c["order"] == "operator_drawn_after_commitment"
        assert c["fair_ordering"] is False
        assert "external commitment" in c["note"]
        # still fully playable (reproducible-simulation mode)
        assert isinstance(hc.crash_points(2)[0], float)

    def test_malformed_beacon_claims_are_not_external_commitments(self):
        assert is_external_commitment(BEACON_SOURCE)
        assert is_external_commitment({"beacon": "drand", "round": 1})
        for bad in (
            None,
            "bitcoin block 1,000,000",                    # free text
            {"beacon": "urandom", "height": 5},           # unknown beacon
            {"beacon": "bitcoin"},                        # missing index
            {"beacon": "bitcoin", "round": 5},            # wrong index key
            {"beacon": "bitcoin", "height": 0},           # non-future index
            {"beacon": "bitcoin", "height": -1},
            {"beacon": "bitcoin", "height": True},        # bool is not an int index
            {"beacon": "bitcoin", "height": "1000000"},   # string index
            {"beacon": "drand", "height": 5},             # mismatched key
        ):
            assert not is_external_commitment(bad), bad
            hc = HashChain("fresh-secret", length=6)
            hc.bind_salt(TEST_SALT, salt_source=bad)
            assert hc.fair_ordering is False
            assert hc.commitment["order"] == "operator_drawn_after_commitment"
        assert set(EXTERNAL_BEACONS) == {"bitcoin", "drand"}

    def test_ground_salt_attack_is_not_certified_fair(self):
        # The round-4 exploit: commit a chain, grind candidate salts until
        # the first rounds all bust below 2x, bind the winner.  The engine
        # must refuse to stamp the rigged chain fair_ordering=True — no
        # matter how the ground salt's salt_source is dressed.
        secret = "grind-target"
        length = 8
        hc = HashChain(secret, length=length)
        chain = build_hash_chain(secret, length)
        first_three = chain[-2:-5:-1]  # play order
        rigged, tries = None, 0
        while rigged is None:
            cand = hashlib.sha256(f"grind {tries}".encode()).hexdigest()
            tries += 1
            if all(crash_point_from_hash(h, cand) < 2.0 for h in first_three):
                rigged = cand
        # (a) dressed as a Bitcoin beacon claim: a ground SHA-256 salt has
        # ~0 leading zero nibbles — impossible for any block, refused
        hc_btc = HashChain(secret, length=length)
        time.sleep(0.002)
        with pytest.raises(CommitmentOrderError, match="leading zero"):
            hc_btc.bind_salt(rigged, salt_source=BEACON_SOURCE,
                             revealed_at=time.time())
        # (b) dressed as a drand claim (no leading-zero structure): binds
        # only as an UNVERIFIED claim; out-of-band resolution of the named
        # round returns a different value -> refuted
        hc_dr = HashChain(secret, length=length)
        time.sleep(0.002)
        hc_dr.bind_salt(rigged,
                        salt_source={"beacon": "drand", "round": 3_366_570},
                        revealed_at=time.time())
        assert all(p < 2.0 for p in hc_dr.crash_points(3))
        assert hc_dr.fair_ordering is False
        assert (hc_dr.commitment["order"]
                == "external_commitment_claimed_unverified")
        real_value = hashlib.sha256(b"the round's real randomness").hexdigest()
        with pytest.raises(CommitmentOrderError, match="does not match"):
            hc_dr.verify_salt_against_beacon(real_value,
                                             resolved_time=time.time())
        assert hc_dr.fair_ordering is False
        assert hc_dr.commitment["order"] == "external_commitment_refuted"
        # (c) confession-string source: recorded as operator-drawn
        hc.bind_salt(rigged, salt_source=f"ground in {tries} tries")
        assert all(p < 2.0 for p in hc.crash_points(3))  # rig worked...
        assert hc.fair_ordering is False                 # ...and is not certified
        assert hc.commitment["order"] == "operator_drawn_after_commitment"

    def test_self_drawn_simulator_cannot_claim_beacon(self):
        with pytest.raises(CommitmentOrderError, match="self-drawn"):
            simulate_chain_targets([2.0], 10, secret_seed="s",
                                   salt_source=BEACON_SOURCE, progress=False)

    def test_preexisting_salt_unfair_even_with_beacon_claim(self):
        with pytest.warns(CommitmentOrderWarning):
            hc = HashChain("fresh-secret", length=6, salt=TEST_SALT,
                           salt_source=BEACON_SOURCE)
        assert hc.fair_ordering is False
        assert hc.commitment["order"] == "salt_preexisting_reproducible_mode"

    def test_stake_salt_variants_refused(self):
        for variant in (STAKE_SALT.upper(), "0x" + STAKE_SALT,
                        "0X" + STAKE_SALT.upper(), " " + STAKE_SALT + " "):
            hc = HashChain("fresh-secret", length=6)
            with pytest.raises(CommitmentOrderError):
                hc.bind_salt(variant)

    def test_salt_at_construction_warns_and_marks_unfair(self):
        with pytest.warns(CommitmentOrderWarning):
            hc = HashChain("fresh-secret", length=6, salt=TEST_SALT)
        assert hc.fair_ordering is False
        assert hc.commitment["order"] == "salt_preexisting_reproducible_mode"
        # still playable (reproducible-simulation mode)
        assert isinstance(hc.crash_points(2)[0], float)

    def test_simulator_caller_salt_warns(self):
        with pytest.warns(CommitmentOrderWarning):
            res = simulate_chain_targets([2.0], 50, secret_seed="s",
                                         salt=TEST_SALT, progress=False)
        assert res["verification"]["commitment"]["fair_ordering"] is False

    def test_replay_of_stakes_published_chain_still_allowed(self):
        # The ONE legitimate use of STAKE_SALT: verifying a game hash that
        # claims to belong to Stake's 2019 chain (explicit salt, no chain
        # generation involved).
        game_hash = hashlib.sha256(b"claimed stake game hash").hexdigest()
        pt = crash_point_from_hash(game_hash, STAKE_SALT)
        assert pt >= 1.0
        res = Crash(2.0).play_round(game_hash, STAKE_SALT)
        assert res["verification"]["salt"] == STAKE_SALT

    def test_honest_two_phase_commit_matches_replay(self):
        # the salt-free commit walk and the salted replay agree on the
        # terminating hash (guard inside simulate_chain_targets)
        res = simulate_chain_targets([2.0], 100, secret_seed="two-phase",
                                     progress=False)
        term = crash_mod._stream_chain_terminator("two-phase", 100,
                                                  progress=False)
        assert res["verification"]["terminating_hash"] == term
