name: Deploy

on:
  push:
    branches: [main]

permissions:
  id-token: write # required for GitHub OIDC
  contents: read
  pull-requests: write # record deployed version on the source PR (devkit version-record)

jobs:
  deploy:
    uses: gingur/devkit/.github/workflows/cf.worker.deploy.yml@bcb233be9ebd2a8b489f23ebca70f8eeefbe2bc1
    with:
      runner: ${{ vars.RUNNER }}
      env: public
      infisicalDomain: ${{ vars.INFISICAL_DOMAIN }}
      infisicalProject: gingur
      infisicalEnv: public
      infisicalPath: /shared/cloudflare/account
      infisicalIdentity: 3642b1dc-7f5c-47c8-8a46-1ba07151e612 # github-troyrhinehart-public
