name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write # required for GitHub OIDC
  pull-requests: write # sticky preview comment

jobs:
  preview:
    uses: gingur/devkit/.github/workflows/cf.worker.preview.yml@main
    with:
      app: troyrhinehart
      domain: troyrhinehart.com
      cfZone: 237ce07141f91c1ef4e427be200e1936 # troyrhinehart.com
      infisicalProject: gingur-7xjq
      infisicalEnv: production
      infisicalPath: /troyrhinehart
      infisicalIdentity: 92d4a017-d03d-4e12-8330-fe7e28bd7c9e # gh-troyrhinehart-preview (env:preview)
    secrets: inherit
