name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write # required for GitHub OIDC
  pull-requests: write # sticky preview comment

jobs:
  preview:
    uses: gingur/devkit/.github/workflows/cf.worker.preview.yml@main
    with:
      app: troyrhinehart
      domain: troyrhinehart.com
      cfZone: 237ce07141f91c1ef4e427be200e1936 # troyrhinehart.com
      infisicalProject: gingur
      infisicalEnv: preview
      infisicalPath: /troyrhinehart/cloudflare
      infisicalIdentity: a81e1fb3-43d6-4bb5-9a7f-241a083f46d5 # gh-cf-deploy
    secrets: inherit
