name: Deploy

on:
  push:
    branches: [main]

permissions:
  id-token: write # required for GitHub OIDC
  contents: read
  pull-requests: write # record deployed version on the source PR (devkit version-record)

jobs:
  deploy:
    uses: gingur/devkit/.github/workflows/cf.worker.deploy.yml@main
    with:
      runner: ${{ vars.RUNNER }}
      env: public
      infisicalProject: gingur
      infisicalEnv: public
      infisicalPath: /troyrhinehart/cloudflare
      infisicalIdentity: a81e1fb3-43d6-4bb5-9a7f-241a083f46d5 # gh-cf-deploy
