name: Rollback

on:
  workflow_dispatch:
    inputs:
      version:
        description: Cloudflare version UUID (blank = previous version)
        type: string
        required: false

permissions:
  contents: read
  id-token: write

jobs:
  rollback:
    uses: gingur/devkit/.github/workflows/cf.worker.rollback.yml@main
    with:
      runner: ${{ vars.RUNNER }}
      version: ${{ inputs.version }}
      infisicalProject: gingur
      infisicalEnv: public
      infisicalPath: /troyrhinehart/cloudflare
      infisicalIdentity: a81e1fb3-43d6-4bb5-9a7f-241a083f46d5 # gh-cf-deploy
    secrets: inherit
