name: Rollback

on:
  workflow_dispatch:
    inputs:
      version:
        description: Cloudflare version UUID (blank = previous version)
        type: string
        required: false

permissions:
  contents: read
  id-token: write

jobs:
  rollback:
    uses: gingur/devkit/.github/workflows/cf.worker.rollback.yml@bcb233be9ebd2a8b489f23ebca70f8eeefbe2bc1
    with:
      runner: ${{ vars.RUNNER }}
      version: ${{ inputs.version }}
      infisicalDomain: ${{ vars.INFISICAL_DOMAIN }}
      infisicalProject: gingur
      infisicalEnv: public
      infisicalPath: /shared/cloudflare/account
      infisicalIdentity: 3642b1dc-7f5c-47c8-8a46-1ba07151e612 # github-troyrhinehart-public
    secrets: inherit
