name: Rollback

on:
  workflow_dispatch:
    inputs:
      version:
        description: Cloudflare version UUID (blank = previous version)
        type: string
        required: false

permissions:
  contents: read
  id-token: write

jobs:
  rollback:
    uses: gingur/devkit/.github/workflows/cf.worker.rollback.yml@main
    with:
      runner: ${{ vars.RUNNER }}
      version: ${{ inputs.version }}
      infisicalProject: gingur
      infisicalEnv: prod
      infisicalPath: /troyrhinehart/cloudflare
      infisicalIdentity: f87b7cde-3016-4e85-84b5-0d077e8833e0
    secrets: inherit
